# Generated by Django 2.0.2 on 2018-02-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('link', models.CharField(max_length=255, verbose_name='Сайт')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('housing', models.IntegerField(blank=True, null=True, verbose_name='Корпус')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to='images', verbose_name='Фото')),
                ('square', models.FloatField(verbose_name='Площадь')),
                ('cost', models.IntegerField(verbose_name='Цена')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
                ('housing', models.IntegerField(blank=True, null=True, verbose_name='Корпус')),
                ('function', models.TextField(verbose_name='Назначение')),
                ('show', models.BooleanField(default=False, verbose_name='Показывать?')),
            ],
        ),
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to='images', verbose_name='Иконка')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('show', models.BooleanField(default=False, verbose_name='Показывать?')),
                ('type', models.IntegerField(choices=[(0, 'Товар'), (1, 'Услуга')], default=1, verbose_name='Тип')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(to='app.ProductService', verbose_name='Товары и услуги'),
        ),
    ]
