# Generated by Django 2.0.2 on 2018-02-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'арендатор', 'verbose_name_plural': 'арендаторы'},
        ),
        migrations.AlterModelOptions(
            name='lease',
            options={'verbose_name': 'аренда', 'verbose_name_plural': 'аренды'},
        ),
        migrations.AlterModelOptions(
            name='productservice',
            options={'verbose_name': 'Товар или услуга', 'verbose_name_plural': 'Товар или услуги'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='title',
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='default', max_length=255, verbose_name='Имя арендатора'),
        ),
    ]
