# Generated by Django 2.0.2 on 2018-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180226_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт'),
        ),
    ]
