# Generated by Django 2.0.2 on 2018-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180227_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок'),
        ),
    ]
