# Generated by Django 2.0.2 on 2018-03-01 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180228_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productservice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productservice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productservice',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='productservice',
            name='show',
        ),
    ]
