# Generated by Django 2.0.2 on 2018-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180301_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Фото')),
            ],
        ),
        migrations.RemoveField(
            model_name='lease',
            name='photo',
        ),
        migrations.AddField(
            model_name='lease',
            name='main_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lease',
            field=models.ForeignKey(on_delete='CASCADE', to='app.Lease'),
        ),
    ]
