# Generated by Django 2.0.2 on 2018-03-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180303_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='main_photo',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Главное фото'),
        ),
    ]
