# Generated by Django 2.0.2 on 2018-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180303_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=None, upload_to='images', verbose_name='Фото'),
        ),
    ]
