# Generated by Django 2.0.2 on 2018-03-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_company_pavilion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Lease'),
        ),
    ]
